### ISSUE TITLE
[Question] What would be the best way to have Gatsby detect changes on the database?

### ISSUE THREAD

**Issue by ItzaMi** [orlowdev/gatsby-source-notion-api#14]
Not an issue but more of a question:

This dependency works great and I was able to move everything to Notion but currently I see that I have to restart everything locally to see the changes that I apply to my databases.

What would be a solution for this?

**Comment by SensyCheung** [comment]
> Not an issue but more of a question:
> 
> This dependency works great and I was able to move everything to Notion but currently I see that I have to restart everything locally to see the changes that I apply to my databases.
> 
> What would be a solution for this?

zapier: Notion + Netlify
