### ISSUE TITLE
Reading more than 100 rows of the database

### ISSUE THREAD

**Issue by edelveiss** [orlowdev/gatsby-source-notion-api#4]
Currently it is only possible to read 100 rows of the database. Would be great if there was an option that could be set to any number. Thanks!

**Comment by orlowdev** [comment]
Hi, good point. I'll try to find some time today to add support for recursive database fetching. Thanks!

**Comment by orlowdev** [comment]
@edelveiss I added recursive DB fetching but I couldn't test it out. Please let me know if it worked. The new code is available in 0.9.0.

**Comment by edelveiss** [comment]
@orlowdev I really appreciate such a quick response! Do you think you could test it? Because it’s still not working on my side and I am still getting only the first 100 rows.
