### ISSUE TITLE
Allowing to query image

### ISSUE THREAD

**Issue by NtwaliHeritier** [orlowdev/gatsby-source-notion-api#6]
It would be great if it was possible to query also images. Thank you🙏

**Comment by orlowdev** [comment]
Hi, I'm not sure if I get the exact problem.

I suggest taking a look at these two short posts I made about `gatsby-source-notion-api`:

- https://orlow.dev/images-in-a-notion-age-with-gatsby-source-notion-api - this one is about images inside the page content
- https://orlow.dev/images-in-files-property-with-gatsby-source-notion-api - and this one is about images inside a **Files** property of the page

If it doesn't help, please let me know - I'll do my best to help. 👍

Also, keep in mind that Notion API is still in beta, it doesn't support most of Notion blocks, including attached images.

**Comment by orlowdev** [comment]
@NtwaliHeritier, did this help?

**Comment by orlowdev** [comment]
Closing this issue as stale, let me know if anything else is needed

**Comment by bennofatius** [comment]
Would love to read through the above linked blog posts, but they appear to be dead links by now?
